temporary: CI: rethnet forking tests: skip infura
because of intermittent "header not found" errors, such as:

  Provider logs
    Infura Forked provider
      automine enabled without pending txs
        simple rpc methods
          ✔ should log basic methods
          ✔ should not log private methods
          ✔ collapse successive calls to the same method
          ✔ should stop collapsing when a different method is called
          ✔ should work when a failed method is called in the middle
        eth_sendTransaction
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful transaction (272ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print an OOG transaction (278ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a contract deployment (355ms)
        eth_sendRawTransaction
thread '<unnamed>' panicked at 'failed to retrieve remote account info for local account initialization: InterpretationError { msg: "unknown field `error`, expected one of `jsonrpc`, `result`, `id` at line 1 column 32", request_body: "[{\"version\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013cd6\"],\"id\":1},{\"version\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013cd6\"],\"id\":2},{\"version\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013cd6\"],\"id\":3}]", expected_type: "Array of success results", response_text: "[{\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"header not found\"}},{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x\"},{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":\"0x15\"}]" }', crates/rethnet_evm/src/state/fork.rs:71:18

  Forked provider
    Using Infura
      ✔ legacy transactions before the berlin hardfork should have type 0 (264ms)
      eth_blockNumber
        ✔ returns the current block number
      eth_call
        ✔ can get DAI total supply (404ms)
        when used in the context of a past block
          when the block number is greater than the fork block number
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
            ✔ does not affect previously added data (625ms)
          when the block number is less or equal to the fork block number
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
            ✔ does not affect previously added storage data (828ms)
Difficulty is larger than U256::max: 10000000000000000000
            ✔ does not affect previously added balance data (820ms)
      eth_getBalance
        ✔ can get the balance of the WETH contract (257ms)
      eth_sendTransaction
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports Ether transfers to remote accounts (331ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports wrapping of Ether (512ms)
      eth_getTransactionByHash
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports local transactions (264ms)
        ✔ supports remote transactions (201ms)
      eth_getTransactionCount
        ✔ should have a non-zero nonce for the first unlocked account
      eth_getTransactionReceipt
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports local transactions (289ms)
        ✔ supports remote transactions (115ms)
      eth_getLogs
        ✔ can get remote logs (169ms)
      evm_revert
Difficulty is larger than U256::max: 10000000000000000000
        ✔ can revert the state of WETH contract to a previous snapshot (369ms)
      hardhat_impersonateAccount
Difficulty is larger than U256::max: 10000000000000000000
        ✔ allows to impersonate a remote EOA (377ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ allows to impersonate a remote contract account (641ms)
      hardhat_stopImpersonatingAccount
        ✔ disables account impersonating (245ms)
      blocks timestamps
        ✔ should use a timestamp relative to the forked block timestamp (2074ms)

  Interval mining provider
    Infura Forked provider
      initialization
        ✔ starts interval mining automatically (2259ms)
      hardhat_reset
        ✔ starts interval mining (4378ms)

  Provider logs
    Infura Forked provider
      automine enabled without pending txs
        simple rpc methods
          ✔ should log basic methods
          ✔ should not log private methods
          ✔ collapse successive calls to the same method
          ✔ should stop collapsing when a different method is called
          ✔ should work when a failed method is called in the middle
        eth_sendTransaction
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful transaction (261ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print an OOG transaction (284ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a contract deployment (331ms)
        eth_sendRawTransaction
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful transaction (2128ms)
thread '<unnamed>' panicked at 'failed to retrieve remote account info for local account initialization: InterpretationError { msg: "unknown field `error`, expected one of `jsonrpc`, `result`, `id` at line 1 column 32", request_body: "[{\"version\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013dd9\"],\"id\":1},{\"version\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013dd9\"],\"id\":2},{\"version\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013dd9\"],\"id\":3}]", expected_type: "Array of success results", response_text: "[{\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"header not found\"}},{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x\"},{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":\"0x15\"}]" }', crates/rethnet_evm/src/state/fork.rs:71:18

  Forked provider
    Using Infura
      ✔ legacy transactions before the berlin hardfork should have type 0 (274ms)
      eth_blockNumber
        ✔ returns the current block number
      eth_call
        ✔ can get DAI total supply (385ms)
        when used in the context of a past block
          when the block number is greater than the fork block number
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
            ✔ does not affect previously added data (608ms)
          when the block number is less or equal to the fork block number
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
            ✔ does not affect previously added storage data (931ms)
Difficulty is larger than U256::max: 10000000000000000000
            ✔ does not affect previously added balance data (963ms)
      eth_getBalance
        ✔ can get the balance of the WETH contract (263ms)
      eth_sendTransaction
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports Ether transfers to remote accounts (328ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports wrapping of Ether (489ms)
      eth_getTransactionByHash
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports local transactions (314ms)
        ✔ supports remote transactions (195ms)
      eth_getTransactionCount
        ✔ should have a non-zero nonce for the first unlocked account
      eth_getTransactionReceipt
Difficulty is larger than U256::max: 10000000000000000000
        ✔ supports local transactions (252ms)
        ✔ supports remote transactions (119ms)
      eth_getLogs
        ✔ can get remote logs (158ms)
      evm_revert
Difficulty is larger than U256::max: 10000000000000000000
        ✔ can revert the state of WETH contract to a previous snapshot (392ms)
      hardhat_impersonateAccount
Difficulty is larger than U256::max: 10000000000000000000
        ✔ allows to impersonate a remote EOA (401ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ allows to impersonate a remote contract account (688ms)
      hardhat_stopImpersonatingAccount
        ✔ disables account impersonating (299ms)
      blocks timestamps
thread '<unnamed>' panicked at 'failed to retrieve remote account info for local account initialization: InterpretationError { msg: "unknown field `error`, expected one of `jsonrpc`, `result`, `id` at line 1 column 72", request_body: "[{\"version\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013e66\"],\"id\":1},{\"version\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013e66\"],\"id\":2},{\"version\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013e66\"],\"id\":3}]", expected_type: "Array of success results", response_text: "[{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"0x0\"},{\"jsonrpc\":\"2.0\",\"id\":2,\"error\":{\"code\":-32000,\"message\":\"header not found\"}},{\"jsonrpc\":\"2.0\",\"id\":3,\"error\":{\"code\":-32000,\"message\":\"header not found\"}}]" }', crates/rethnet_evm/src/state/fork.rs:71:18

  Block's baseFeePerGas
    Infura Forked provider
      Initial base fee per gas
        When forking from a remote network the forked block must have the right value
          With an initialBaseFeePerGas config value
            ✔ should use the given value (2230ms)
          Without an initialBaseFeePerGas config value
            ✔ Should use the same base fee as the one remote networks's forked block (2546ms)
            ✔ should compute the next base fee correctly when london is activated (2202ms)
            ✔ should compute the next base fee correctly when arrowGlacier is activated (2159ms)
      Base fee adjustment
        When not forking
thread '<unnamed>' panicked at 'failed to retrieve remote account info for local account initialization: InterpretationError { msg: "unknown field `error`, expected one of `jsonrpc`, `result`, `id` at line 1 column 32", request_body: "[{\"version\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013eea\"],\"id\":1},{\"version\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013eea\"],\"id\":2},{\"version\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1013eea\"],\"id\":3}]", expected_type: "Array of success results", response_text: "[{\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"header not found\"}},{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x\"},{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":\"0x15\"}]" }', crates/rethnet_evm/src/state/fork.rs:71:18

  Provider logs
    Infura Forked provider
      automine enabled without pending txs
        simple rpc methods
          ✔ should log basic methods
          ✔ should not log private methods
          ✔ collapse successive calls to the same method
          ✔ should stop collapsing when a different method is called
          ✔ should work when a failed method is called in the middle
        eth_sendTransaction
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful transaction (281ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print an OOG transaction (260ms)
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a contract deployment (342ms)
        eth_sendRawTransaction
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful transaction (2200ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
          ✔ should print a failed transaction (3116ms)
        eth_call
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a successful call (328ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
          ✔ should print a failed call (347ms)
          ✔ should warn when calling an account that is not a contract (307ms)
        eth_estimateGas
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 20020000000000000000
          ✔ shouldn't print anything when the gas estimation is successful (367ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
          ✔ should print extra details when the gas estimation fails (356ms)
      automine enabled with pending txs
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ one pending tx, sent tx at the end of the block (300ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ one pending tx, sent tx at the start of the block (269ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 20020000000000000000
        ✔ three pending txs, two txs per block, sent tx in second block (435ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 20020000000000000000
        ✔ three pending txs, two txs per block, sent tx can be mined immediately (399ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 20020000000000000000
Difficulty is larger than U256::max: 20020000000000000000
        ✔ should show the stack trace in the block list and at the end (388ms)
      hardhat_intervalMine
        ✔ should only print the mined block when there are no pending txs (279ms)
        ✔ should collapse the mined block info (264ms)
        ✔ should stop collapsing when a different method is called (259ms)
Difficulty is larger than U256::max: 10000000000000000000
        ✔ should print a block with one transaction (277ms)
Difficulty is larger than U256::max: 10000000000000000000
Difficulty is larger than U256::max: 10000000000000000000
        ✔ should print a block with two transactions (266ms)
thread '<unnamed>' panicked at 'failed to retrieve remote account info for local account initialization: InterpretationError { msg: "unknown field `error`, expected one of `jsonrpc`, `result`, `id` at line 1 column 32", request_body: "[{\"version\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1014bfb\"],\"id\":1},{\"version\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1014bfb\"],\"id\":2},{\"version\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xbe862ad9abfe6f22bcb087716c7d89a26051f74c\",\"0x1014bfb\"],\"id\":3}]", expected_type: "Array of success results", response_text: "[{\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"header not found\"}},{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x\"},{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":\"0x15\"}]" }', crates/rethnet_evm/src/state/fork.rs:71:18