fix panic from nested tokio runtimes
typescript tests were intermittently failing with panics like shown
below.

thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/gene/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic
   1: tokio::runtime::blocking::shutdown::Receiver::wait
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
   5: core::ptr::drop_in_place<rethnet_evm::db::fork::ForkDatabase>
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::harness::Harness<T,S>::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run
  11: tokio::macros::scoped_tls::ScopedKey<T>::set
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(661), ...)', /home/gene/dev/nomiclabs/rethnet/crates/rethnet_evm/src/db/sync.rs:284:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: <rethnet_evm::db::sync::AsyncDatabase<E> as core::ops::drop::Drop>::drop
   4: alloc::sync::Arc<T>::drop_slow
   5: napi::bindgen_runtime::raw_finalize_unchecked
   6: _ZN4node13CallbackQueueIvJPNS_11EnvironmentEEE12CallbackImplIZN15node_napi_env__13CallFinalizerILb1EEEvPFvP10napi_env__PvS9_ES9_S9_EUlS2_E0_E4CallES2_
   7: _ZN4node11Environment27RunAndClearNativeImmediatesEb
   8: _ZN4node11Environment14CheckImmediateEP10uv_check_s
   9: uv__run_check
             at /home/iojs/build/ws/out/../deps/uv/src/unix/loop-watcher.c:67:1
  10: uv_run
             at /home/iojs/build/ws/out/../deps/uv/src/unix/core.c:398:5
  11: _ZN4node13SpinEventLoopEPNS_11EnvironmentE
  12: _ZN4node16NodeMainInstance3RunEv
  13: _ZN4node5StartEiPPc
  14: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  16: _start